name: Tuya Cloud → MQTT Bridge
version: "1.0.0"
slug: tuya-cloud-mqtt-bridge
description: Publishes a Tuya (Smart Life) device to Home Assistant via MQTT Discovery using Tuya Cloud.
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
options:
  access_id: ""
  access_key: ""
  region: "eu"            # eu | us | cn | in
  username: ""            # Tuya/Smart Life email or phone
  password: ""
  country_code: "39"      # e.g., 39 for Italy
  app_schema: "smartlife" # smartlife | tuyaSmart
  device_id: ""
  entity_id: "tuya_sensor"
  name: "Tuya Sensor"
  device_class: "opening"
  poll_interval: 20
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  dps_active: null
  dps_battery: null
schema:
  access_id: str
  access_key: str
  region: list(eu|us|cn|in)
  username: str
  password: password
  country_code: str
  app_schema: str
  device_id: str
  entity_id: str
  name: str
  device_class: str
  poll_interval: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  dps_active: "int?"
  dps_battery: "int?"
